services:
  mysql-service:
    container_name: mysql-container
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - "./db-data24:/var/lib/mysql"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - '3306:3306'
    networks:
      - microservices-network
    environment:
      - MYSQL_ROOT_PASSWORD=yourpassword
      - MYSQL_DATABASE=authenticationdb

  php-myadmin-service:
    container_name: php-myadmin-container
    depends_on:
      - mysql-service
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '7081:80'
    networks:
      - microservices-network
    environment:
      - PMA_HOST=mysql-container
      - MYSQL_ROOT_PASSWORD=yourpassword

  microservice_auth:
    container_name: ms_authentication
    depends_on:
      - mysql-service
      - eureka-service
    build:
      context: ./auth-service/
      dockerfile: Dockerfile
    ports:
      - '8095:8095'
    networks:
      - microservices-network
    restart: unless-stopped
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - eureka.client.service-url.defaultZone=http://eureka-container:8761/eureka
      - spring.datasource.url=jdbc:mysql://mysql-container:3306/authenticationdb
      - spring.datasource.username=root
      - spring.datasource.password=yourpassword

  microservice_medecin:
    container_name: medecin-container
    depends_on:
      - mysql-service
      - eureka-service
    build:
      context: ./medecin/
      dockerfile: Dockerfile
    ports:
      - '8084:8080'
    networks:
      - microservices-network
    restart: unless-stopped
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - eureka.client.service-url.defaultZone=http://eureka-container:8761/eureka
      - spring.datasource.url=jdbc:mysql://mysql-container:3306/Medecindb
      - spring.datasource.username=root
      - spring.datasource.password=yourpassword

  microservice_patient:
    container_name: patient-container
    depends_on:
      - mysql-service
      - eureka-service
    build:
      context: ./patient/
      dockerfile: Dockerfile
    ports:
      - '8085:8080'
    networks:
      - microservices-network
    restart: unless-stopped
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - eureka.client.service-url.defaultZone=http://eureka-container:8761/eureka
      - spring.datasource.url=jdbc:mysql://mysql-container:3306/Patientdb
      - spring.datasource.username=root
      - spring.datasource.password=yourpassword

  microservice_rendezvous:
    container_name: rendezvous-container
    depends_on:
      - mysql-service
      - eureka-service
    build:
      context: ./rendez-vous/
      dockerfile: Dockerfile
    ports:
      - '8086:8080'
    networks:
      - microservices-network
    restart: unless-stopped
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - eureka.client.service-url.defaultZone=http://eureka-container:8761/eureka
      - spring.datasource.url=jdbc:mysql://mysql-container:3306/Rendezvousdb
      - spring.datasource.username=root
      - spring.datasource.password=yourpassword

  api_gateway_service:
    container_name: api-gateway-container
    depends_on:
      - eureka-service
    build:
      context: ./api-gateway/
      dockerfile: Dockerfile
    ports:
      - '8762:8762'
    networks:
      - microservices-network
    restart: unless-stopped
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-container:8761/eureka
      - spring.cloud.gateway.discovery.locator.enabled=true

  eureka-service:
    container_name: eureka-container
    build:
      context: ./eureka/
      dockerfile: Dockerfile
    ports:
      - '8761:8761'
    networks:
      - microservices-network
    restart: always

networks:
  microservices-network:
    driver: bridge
